/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_sys;

/**
 *
 * @author Salitha Kaweendra
 */
public class mainp extends javax.swing.JPanel {

    /**
     * Creates new form mainp
     */
    public mainp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel3 = new roundPanel.roundedPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/library.jpg"))); // NOI18N
        roundedPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundedPanel3MouseEntered(evt);
            }
        });
        roundedPanel3.setLayout(null);
        add(roundedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 665));
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel3MouseEntered

    }//GEN-LAST:event_roundedPanel3MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static roundPanel.roundedPanel roundedPanel3;
    // End of variables declaration//GEN-END:variables
}
